stages:

  data_ingestion:

    cmd: python src/components/data_ingestion.py

    deps:
      - src/components/data_ingestion.py
      - configs/config.py
      - configs/mongo_configuration.py
      - configs/settings.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py

    outs:
      - data/raw/raw.csv
      - data/feature/train.csv
      - data/feature/test.csv
  
  # ...existing code...

  data_validation:
    cmd: python src/components/data_validation.py

    deps:
      - src/components/data_validation.py
      - data/feature/train.csv
      - data/feature/test.csv
      - configs/schema.yaml
      - configs/config.py
      - configs/settings.py
      - src/entity/artifact_entity.py
      - src/utils/common.py

    outs:
      - artifacts/reports/validation.json
  
  data_preproccessing:
    cmd: python src/components/data_preproccess.py

    deps:
     - src/components/data_preproccess.py
     - configs/config.py
     - configs/settings.py
     - src/utils/common.py

    outs:
     - data/preproccessed/train.csv
     - data/preproccessed/test.csv

  data_transformation:
     cmd: python src/components/data_transformation.py

     deps:
       - src/components/data_transformation.py
       - configs/config.py
       - configs/settings.py
       - src/utils/common.py
      
     outs:
       - artifacts/transform/train.csv
       - artifacts/transform/test.csv
       - artifacts/transform/preproccessor/preproccessor.pkl

  model_trainer:
    cmd: python src/components/model_trainer.py

    deps:
      - src/components/model_trainer.py
      - configs/config.py
      - configs/settings.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
      - src/utils/common.py
      - artifacts/transform/train.csv
      - artifacts/transform/test.csv
      - artifacts/transform/preproccessor/preproccessor.pkl
      - params.yaml

    outs:
      - artifacts/models/model.pkl
      - artifacts/prediction/prediction_train.csv
      - artifacts/prediction/prediction_test.csv
       
    